### ISSUE TITLE
The URL generated by this plugin misses the suffix ".md "

### ISSUE THREAD

**Issue by greenhands-always** [kometenstaub/copy-publish-url#8]
Thank you for this useful plugin. It means a lot to me.
As the title says, the URL I get can't be open directly because the correct URL is "URL.md". So I try to configure the plugin, only to find that the suffix isn't configurable. To make it worse, I am new to TypeScript so that I confront troubles when I try to modify the source code.
I'd appreciate it if you could help me.

**Comment by claremacrae** [comment]
Which URL are you taking about, @greenhands-always ?

- The one to go to the Publish site?
- The one to go to the file on GitHub?
- The one to go to the history for the file on GitHub?

**Comment by claremacrae** [comment]
Please can you test again, and give us an example, showing the actual URL the plugin gives, and the one that you expect?

**Comment by nbossard** [comment]
Hello Clare, thanks too for your plugin.
Got the same issue, so adding my two cents.

Here is the URL I got using menu "Copy publish URL": 

<https://gitlab.tech.toto/mah/documentation/-/tree/master/puml_schemas/sms_authent/README>

Here is the URL I expected : 

<https://gitlab.tech.toto/mah/documentation/-/tree/master/puml_schemas/sms_authent/README.md>

(note the final extension ".md")

**Comment by nbossard** [comment]
Would love to make a fix proposal for this, should not be complex. Would you help me configuring the dev environment when modifying a plugin like your?
Looked at the source file, it is "compressed" so not modifiable directly.

**Comment by claremacrae** [comment]
> Hello Clare, thanks too for your plugin. Got the same issue, so adding my two cents.
> 
> Here is the URL I got using menu "Copy publish URL":
> 
> https://gitlab.tech.toto/mah/documentation/-/tree/master/puml_schemas/sms_authent/README
> 
> Here is the URL I expected :
> 
> https://gitlab.tech.toto/mah/documentation/-/tree/master/puml_schemas/sms_authent/README.md
> 
> (note the final extension ".md")

But that isn't an [Obsidian Publish](https://obsidian.md/publish) URL, surely - it's a gitlab URL.

So I wouldn't expect it to work.

The README is quite clear (my emphasis):

> This plugin adds a command which lets you copy the URL of a note for your **Obsidian Publish** site.

Maybe the other feature - to see GitHub history - might work for GitLab - I've no idea...

> As of v0.4.0, you can open the current note's Git commit history on GitHub. It is turned off by default. You need to set the repository URL and the branch name for it to work.

**Comment by claremacrae** [comment]
> As the title says, the URL I get can't be open directly because the correct URL is "URL.md". 

@greenhands-always  This plugin links to Obsidian Publish pages - which do not have a `.md` in the published URL.

There's more info in my reply above...

**Comment by claremacrae** [comment]
> Hello Clare, thanks too for your plugin.

@nbossard - it's not mine, I am a happy user of this plugin...

I was just trying to help out @kometenstaub, who gets the credit!

**Comment by nbossard** [comment]
oups sorry for the confusion
